const weeklyPrograms={
hypertrophy:{label:"Hypertrophy",days:{
Monday:{title:"Upper Push Hypertrophy",exercises:["Bench Press 4x8","Incline DB Press 3x10","DB Shoulder Press 3x10","Lateral Raise 3x15","Tricep Pushdown 3x12","Plank 3x60 sec"]},
Tuesday:{title:"Lower Hypertrophy",exercises:["Back Squat 4x8","Romanian Deadlift 4x10","Walking Lunge 3x12 each","Leg Press 3x15","Hamstring Curl 3x12","Calf Raise 4x20"]},
Wednesday:{title:"Pull Hypertrophy",exercises:["Weighted Pull-Up 4x6-8","Seated Row 4x10","Lat Pulldown 3x12","Chest Supported Row 3x12","Rear Delt Fly 3x15","Bicep Curl 3x12"]},
Thursday:{title:"Zone 2 + Mobility",exercises:["Zone 2 Run 30 min","Knee to Wall 3x10 each","Couch Stretch 90 sec each","90/90 Hip Stretch 60 sec each","Deep Squat Hold 2 min"]},
Friday:{title:"Upper Full Hypertrophy",exercises:["DB Bench Press 4x10","Pull-Up 4xMax","Shoulder Press 3x10","Cable Row 3x12","Lateral Raise 3x15","Face Pull 3x15"]},
Saturday:{title:"Long Run + Core",exercises:["Long Run 3-5km","Hanging Leg Raise 3x12","Side Plank 3x45 sec each","Calf Raise 3x20"]},
Sunday:{title:"Recovery",exercises:["Walk 30 min","Child's Pose 60 sec","Open Book 10 each","Pigeon Stretch 60 sec each"]}}},
tactical:{label:"Tactical Fitness",days:{
Monday:{title:"Tactical Upper",exercises:["Weighted Pull-Up 5x5","DB Bench Press 4x10","Farmer Carry 5x40m","Push-Up 4xMax","Plank 3x90 sec"]},
Tuesday:{title:"Run Intervals",exercises:["Run 400m x6","Walk 90 sec between","Calf Stretch 60 sec each","Tibialis Raise 3x15"]},
Wednesday:{title:"Loaded Lower",exercises:["Trap Bar Deadlift 5x5","Sandbag Squat 5x10","Walking Lunge 4x20m","Sled Push 6x20m","Farmer Carry 4x40m"]},
Thursday:{title:"Mobility + Zone 2",exercises:["Zone 2 Run 35 min","Couch Stretch 90 sec each","90/90 Hip Stretch 60 sec each","Open Book 10 each"]},
Friday:{title:"Work Capacity Circuit",exercises:["Row 500m x4","Kettlebell Swing 4x20","Burpee 4x10","Sandbag Carry 4x50m","Sit-Up 4x25"]},
Saturday:{title:"Ruck / Pack Walk",exercises:["Pack Walk 45-60 min","Step-Up 4x20 each","Calf Raise 4x25","Deep Squat Hold 2 min"]},
Sunday:{title:"Recovery",exercises:["Walk 30 min","Recovery Reset Mobility 15 min"]}}},
police:{label:"Police Tactical Unit Prep",days:{
Monday:{title:"Bodyweight Test Prep",exercises:["Push-Up 2 min test","Sit-Up 2 min test","Pull-Up Max Test","Plank Max Hold"]},
Tuesday:{title:"Shuttle Conditioning",exercises:["Shuttle Run 10x20m","Burpee 5x10","Walking Lunge 4x20m","Stretch 10 min"]},
Wednesday:{title:"Strength Base",exercises:["Back Squat 4x6","Bench Press 4x6","Pull-Up 5xMax","Farmer Carry 4x40m"]},
Thursday:{title:"Aerobic Base",exercises:["Zone 2 Run 35 min","Mobility 15 min"]},
Friday:{title:"Selection Circuit",exercises:["Push-Up 50 total","Pull-Up 30 total","Sandbag Carry 800m total","Bear Crawl 5x20m","Plank 5 min total"]},
Saturday:{title:"1km / 5km Run Work",exercises:["1km Time Trial","Easy Jog 15 min","Calf Stretch","Hip Mobility"]},
Sunday:{title:"Recovery",exercises:["Walk 30 min","Legs and Back Mobility"]}}},
travel:{label:"Caravan / Travel",days:{
Monday:{title:"Campground Upper",exercises:["Push-Up 5x15","Band Row 5x20","Pike Push-Up 4x10","Plank 3x60 sec"]},
Tuesday:{title:"Run + Mobility",exercises:["Easy Run 25 min","Knee to Wall","Couch Stretch","Deep Squat Hold"]},
Wednesday:{title:"Campground Lower",exercises:["Bodyweight Squat 5x25","Reverse Lunge 4x15 each","Step-Up 4x15 each","Calf Raise 4x25"]},
Thursday:{title:"Recovery Mobility",exercises:["Walk 30 min","90/90 Hip Stretch","Pigeon Stretch","Open Book"]},
Friday:{title:"Travel Circuit",exercises:["Push-Up 15","Air Squat 25","Band Row 20","Mountain Climber 30","Repeat 5 rounds"]},
Saturday:{title:"Long Walk / Hike",exercises:["Walk or Hike 45-90 min","Stretch 10 min"]},
Sunday:{title:"Rest",exercises:["Easy walk","Light mobility"]}}}
};
let activeWorkout=null,activeIndex=0;
function get(k){return JSON.parse(localStorage.getItem(k)||"[]")}function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function today(){return new Date().toISOString().slice(0,10)}
function init(){["foodDate"].forEach(id=>{let e=document.getElementById(id);if(e)e.value=today()});populateSelectors();loadNutritionTargets();previewMission();renderAll();if("serviceWorker" in navigator){navigator.serviceWorker.register("./sw.js")}}
function populateSelectors(){let p=Object.keys(weeklyPrograms).map(k=>`<option value="${k}">${weeklyPrograms[k].label}</option>`).join("");missionProgram.innerHTML=p;programView.innerHTML=p;sets.innerHTML=Array.from({length:12},(_,i)=>`<option ${i+1===3?"selected":""}>${i+1}</option>`).join("");reps.innerHTML=Array.from({length:30},(_,i)=>`<option ${i+1===8?"selected":""}>${i+1}</option>`).join("");rpe.innerHTML=Array.from({length:10},(_,i)=>`<option ${i+1===8?"selected":""}>${i+1}/10</option>`).join("");updateMissionDays()}
function updateMissionDays(){let days=Object.keys(weeklyPrograms[missionProgram.value].days);missionDay.innerHTML=days.map(d=>`<option>${d}</option>`).join("");previewMission()}
function selectedDayWorkout(){let base=weeklyPrograms[missionProgram.value].days[missionDay.value];let ready=missionReady.value;if(ready==="red")return {title:"Recovery Replacement",exercises:["Walk 20-30 min","Child's Pose 60 sec","Couch Stretch 90 sec each","90/90 Hip Stretch 60 sec each","Deep Breathing 3 min"]};if(ready==="amber")return {...base,title:base.title+" - Reduced Volume",exercises:base.exercises.slice(0,Math.max(3,Math.ceil(base.exercises.length*.7)))};return base}
function previewMission(){if(!missionProgram.value)return;let w=selectedDayWorkout();missionPreview.innerHTML=`<div class="bigtitle">${missionDay.value}: ${w.title}</div>${w.exercises.map(x=>`<div class="exercise">${x}</div>`).join("")}`}
function startMission(){activeWorkout=selectedDayWorkout();activeWorkout.day=missionDay.value;activeWorkout.program=weeklyPrograms[missionProgram.value].label;activeIndex=0;set("activeWorkout",activeWorkout);localStorage.setItem("activeIndex","0");renderActive();show("active")}
function renderActive(){activeWorkout=activeWorkout||get("activeWorkout");activeIndex=parseInt(localStorage.getItem("activeIndex")||"0");if(!activeWorkout||!activeWorkout.exercises){activeSession.innerHTML="<div class='small'>No active session. Start one from Mission.</div>";return}if(activeIndex>=activeWorkout.exercises.length){activeSession.innerHTML=`<h3>Session Complete</h3><div class="small">${activeWorkout.program||""} - ${activeWorkout.title}</div><button onclick="finishWorkout()">Finish Workout</button>`;return}let ex=activeWorkout.exercises[activeIndex],last=lastForExercise(ex);activeSession.innerHTML=`<div class="small">${activeWorkout.day||""} | Exercise ${activeIndex+1} of ${activeWorkout.exercises.length}</div><div class="bigtitle">${cleanName(ex)}</div><div class="small">Programmed: ${ex}</div>${last?`<div class="prtarget"><b>Last:</b> ${last.weight}kg | ${last.sets} | ${last.rpe}</div>`:""}<div class="grid3"><div><label>Sets</label><select id="aSets">${sets.innerHTML}</select></div><div><label>Reps</label><select id="aReps">${reps.innerHTML}</select></div><div><label>Weight kg</label><input id="aWeight" type="number" step="0.5"></div></div><label>RPE</label><select id="aRpe">${rpe.innerHTML}</select><label>Notes</label><textarea id="aNotes"></textarea><button onclick="saveActiveExercise()">Save + Next</button><button class="secondary" onclick="skipExercise()">Skip</button>`}
function saveActiveExercise(){let ex=activeWorkout.exercises[activeIndex],w=parseFloat(aWeight.value)||0,r=parseInt(aReps.value)||0,s=parseInt(aSets.value)||0;let logs=get("logs");logs.push({date:today(),program:activeWorkout.program,workout:activeWorkout.title,ex,sets:`${s} x ${r}`,setsNum:s,repsNum:r,weight:w,weightNum:w,e1rm:calcE1RM(w,r),rpe:aRpe.value,notes:aNotes.value});set("logs",logs);activeIndex++;localStorage.setItem("activeIndex",String(activeIndex));renderAll();renderActive()}
function skipExercise(){activeIndex++;localStorage.setItem("activeIndex",String(activeIndex));renderActive()}
function finishWorkout(){let s=get("sessions");s.push({date:today(),program:activeWorkout.program,title:activeWorkout.title});set("sessions",s);localStorage.removeItem("activeWorkout");localStorage.removeItem("activeIndex");activeWorkout=null;activeIndex=0;renderAll();show("mission")}
function renderProgramView(){let pg=weeklyPrograms[programView.value];programDays.innerHTML=Object.entries(pg.days).map(([d,w])=>`<div class="card"><h3>${d}: ${w.title}</h3>${w.exercises.map(x=>`<div class="exercise">${x}</div>`).join("")}</div>`).join("")}
function show(id){document.querySelectorAll("section").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));[...document.querySelectorAll(".tab")].find(b=>b.textContent.toLowerCase().includes(id==="prs"?"prs":id))?.classList.add("active");renderAll()}
function previewMealPhoto(e){let file=e.target.files[0];if(!file)return;let url=URL.createObjectURL(file);mealPreview.src=url;mealPreview.style.display="block";aiResult.style.display="none"}
function mockAIAnalysis(){aiResult.style.display="block";aiResult.innerHTML="<b>AI connection required:</b><br>This button is ready for backend/API integration. Once connected, it will identify food items, estimate portion size, calories, protein, carbs and fat, then pre-fill the meal form for confirmation."}
function saveNutritionTargets(){localStorage.setItem("calTarget",calTarget.value||"");localStorage.setItem("proteinTarget",proteinTarget.value||"");renderNutrition()}
function loadNutritionTargets(){calTarget.value=localStorage.getItem("calTarget")||"";proteinTarget.value=localStorage.getItem("proteinTarget")||""}
function saveFood(){let f=get("foods");f.push({date:foodDate.value||today(),name:foodName.value,cals:+foodCals.value||0,protein:+foodProtein.value||0,carbs:+foodCarbs.value||0,fat:+foodFat.value||0});set("foods",f);["foodName","foodCals","foodProtein","foodCarbs","foodFat"].forEach(id=>document.getElementById(id).value="");renderAll()}
function todayFoods(){return get("foods").filter(f=>f.date===today())}
function renderNutrition(){let foods=todayFoods();let c=foods.reduce((s,f)=>s+f.cals,0),p=foods.reduce((s,f)=>s+f.protein,0),carbs=foods.reduce((s,f)=>s+f.carbs,0),fat=foods.reduce((s,f)=>s+f.fat,0);let ct=+localStorage.getItem("calTarget")||0,pt=+localStorage.getItem("proteinTarget")||0;nutritionToday.innerHTML=`<div class="grid"><div class="metric"><span>Calories</span><b>${c}${ct?`/${ct}`:""}</b></div><div class="metric"><span>Protein</span><b>${p}g${pt?`/${pt}g`:""}</b></div><div class="metric"><span>Carbs</span><b>${carbs}g</b></div><div class="metric"><span>Fat</span><b>${fat}g</b></div></div>${ct?`<br><div class="progressbar"><span style="width:${Math.min(100,Math.round(c/ct*100))}%"></span></div>`:""}`;foodLogs.innerHTML=get("foods").slice(-15).reverse().map(f=>`<div class="logitem"><b>${f.name}</b> — ${f.cals} cal<br>${f.protein}g protein | ${f.carbs}g carbs | ${f.fat}g fat<br><span class="small">${f.date}</span></div>`).join("")||"<div class='small'>No foods logged yet.</div>"}
function saveQuickLog(){let w=parseFloat(weight.value)||0,r=parseInt(reps.value)||0,s=parseInt(sets.value)||0;let logs=get("logs");logs.push({date:today(),ex:quickExercise.value,sets:`${s} x ${r}`,setsNum:s,repsNum:r,weight:w,weightNum:w,e1rm:calcE1RM(w,r),rpe:rpe.value,notes:notes.value});set("logs",logs);quickExercise.value="";weight.value="";notes.value="";renderAll()}
function renderLogs(){logs.innerHTML=get("logs").slice(-12).reverse().map(l=>`<div class="logitem"><b>${l.ex}</b> — ${l.weight||0}kg<br>${l.workout||""} | ${l.sets} | RPE ${l.rpe||""}<br><span class="small">${l.notes||""}</span></div>`).join("")||"<div class='small'>No logs yet.</div>"}
function cleanName(name){return name.replace(/ - .*/,"").replace(/\s+\d+x.*/i,"").trim()}
function normaliseExerciseName(name){return cleanName(name||"").replace(/\s+\d+km.*$/i,"").trim()}
function calcE1RM(weight,reps){return weight&&reps?weight*(1+reps/30):0}
function lastForExercise(name){let ex=normaliseExerciseName(name);return get("logs").slice().reverse().find(l=>normaliseExerciseName(l.ex)===ex)}
function buildPRs(){let prs={};get("logs").forEach(l=>{let w=+l.weightNum||+l.weight||0,r=+l.repsNum||0;if(!w||!r)return;let ex=normaliseExerciseName(l.ex),e=l.e1rm||calcE1RM(w,r);if(!prs[ex]||e>prs[ex].e1rm)prs[ex]={exercise:ex,weight:w,reps:r,date:l.date,e1rm:e}});return Object.values(prs).sort((a,b)=>b.e1rm-a.e1rm)}
function targetForNewPR(p){let target=p.e1rm+.1;let nextWeight=Math.max(Math.ceil(((target/(1+p.reps/30))*2))/2,p.weight+.5);let repsNeeded=Math.floor(((target/p.weight)-1)*30)+1;return {a:`${nextWeight.toFixed(nextWeight%1?1:0)}kg x ${p.reps}`,b:`${p.weight.toFixed(p.weight%1?1:0)}kg x ${Math.max(repsNeeded,p.reps+1)}`}}
function renderPRs(){let prs=buildPRs();prList.innerHTML=prs.length?prs.map(p=>{let t=targetForNewPR(p);return `<div class="logitem"><h3>${p.exercise}</h3><b>PB:</b> ${p.weight}kg x ${p.reps}<br><span class="small">Est 1RM: ${p.e1rm.toFixed(1)}kg</span><div class="prtarget"><b>To beat:</b><br>${t.a}<br>${t.b}</div></div>`}).join(""):"<div class='small'>No PRs yet.</div>"}
function renderDashboard(){let foods=todayFoods();mSessions.textContent=get("sessions").length;mCals.textContent=foods.reduce((s,f)=>s+f.cals,0);mProtein.textContent=foods.reduce((s,f)=>s+f.protein,0)+"g";mPRs.textContent=buildPRs().length}
function renderAll(){renderDashboard();renderProgramView();renderActive();renderNutrition();renderLogs();renderPRs()}
init();